---
- name: Install i3
  become: true
  pacman:
    name: "i3-wm,i3blocks"
    state: present
    update_cache: yes

- name: Copy dotfiles
  loop:
    - src: "../dotfiles/i3wm/i3_config"
      dest: "$HOME/.config/i3/config"
    - src: "../dotfiles/i3wm/i3blocks_config"
      dest: "$HOME/.config/i3blocks/config"
    - src: "../dotfiles/.picom.conf"
      dest: "$HOME/.picom.conf"
  include_tasks: safe_copy.yml
