---
- name: Install i3
  become: true
  vars:
    i3_packages:
      - i3-wm
      - i3blocks
      - i3lock
      - xss-lock
  pacman:
    name: "{{i3_packages}}"
    state: present
    update_cache: yes

- name: Copy dotfiles
  loop:
    - src: "../dotfiles/i3wm/i3_config"
      dest: "$HOME/.config/i3/config"
    - src: "../dotfiles/i3wm/polybar_config.ini"
      dest: "$HOME/.config/polybar/config.ini"
    - src: "../dotfiles/rofi/config.rasi"
      dest: "$HOME/.config/rofi/config.rasi"
    - src: "../dotfiles/rofi/theme.rasi"
      dest: "$HOME/.config/rofi/theme.rasi"
    - src: "../dotfiles/i3wm/polybar_launch.sh"
      dest: "$HOME/.config/polybar/launch.sh"
    - src: "../dotfiles/.picom.conf"
      dest: "$HOME/.picom.conf"
  include_tasks: safe_copy.yml
