---
- name: Create dir
  ignore_errors: true
  file:
    path: "{{item['dest'] | dirname }}"
    state: directory

- name: Safe copy file
  copy:
    src: "{{item['src']}}"
    dest: "{{item['dest']}}"
