[package]
name = "linux-setup"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/s3rius/linux_setup.git"

[dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
clap = { version = "4.5.38", features = ["derive"] }
rand = "0.9.1"
rpassword = "7.4.0"
rust-embed = "8.7.1"
serde = { version = "1.0.219", features = ["derive"] }
shellexpand = { version = "3.1.1", features = ["full"] }
toml = "0.8.22"
toml_edit = { version = "0.22.26", features = ["serde"] }
users = "0.11.0"
