[linux]
# Name of the bootloader in BIOS
bootloader_id = "I use arch BTW"
# Where EFI partition is mounted inside chroot.
efi_mountpoint = "/boot/EFI"
# Username for your user.
username = "s3rius"
# Groups to assign to this user.
groups = ["docker", "libvirt"]
# Locales to generate.
locales = ["en_US.UTF-8", "ru_RU.UTF-8"]
vconsole_keymap = "us"
# Current timezone.
timezone = "Europe/Belgrade"
# Chezmoi compatible dotfiles repo.
# Will be passed to init.
# If you don't have such repositroy, just remove this line.
dotfiles_repo = "s3rius/dotfiles"
