- name: "Installing window manager"
  hosts: local
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Install X11
      become: true
      vars:
        xorg_packages:
          - xorg
          - xorg-xclock
          - xorg-xinit
          - xterm
          - xdg-utils
          - xclip
          - unclutter
          - picom
          - nitrogen
          - maim
          - gnome-keyring
          - dmenu
          - lightdm
          - lightdm-gtk-greeter
      pacman:
        name: "{{xorg_packages}}"
        state: present
        update_cache: yes

    - name: Configure lightdm
      become: true
      lineinfile:
        dest: /etc/lightdm/lightdm.conf
        state: present
        regexp: "^#greeter-session=.*$"
        line: "greeter-session=lightdm-gtk-greeter"
