- name: "Installing dependencies"
  hosts: "local"
  vars_files:
    - "../vars.yml"
  tasks:
    - name: "Installing packages from pacman"
      ansible.builtin.command:
        cmd: "pacman -Syu --noconfirm --needed {{pacman_packages | join(' ')}}"
