- name: "Installing dependencies"
  hosts: "local"
  vars_files:
    - "../vars.yml"
  tasks:
    - name: "Installing packages from pacman"
      pacman:
        name: "{{pacman_packages | join(',')}}"
        state: present
        update_cache: yes
