- name: "Installing dependencies"
  hosts: "local"
  vars_files:
    - "../vars.yml"
  tasks:
    - name: "Install packages from source"
      loop: "{{custom_packages}}"
      include_tasks: taskgroups/install_from_git.yml
    - name: "Install packages from pikaur"
      