- name: "Installing dependencies"
  hosts: "local"
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Install pikaur
      vars:
        item:
          git_url: https://aur.archlinux.org/pikaur.git
          build_command: yes | makepkg -fsri
      include_tasks: taskgroups/install_from_git.yml

    - name: "Install packages from AUR"
      command:
        cmd: "pikaur -Syu --needed --noconfirm --noedit {{pikaur_deps | join(' ')}}"

    - name: "Build packages from source"
      loop: "{{custom_packages}}"
      include_tasks: taskgroups/install_from_git.yml
