- name: "Installing window manager"
  hosts: local
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Install X11
      become: true
      vars:
        xorg_packages:
          - xorg
          - xorg-xclock
          - xorg-xinit
          - xterm
          - xdg-utils
          - xclip
          - unclutter
          - nitrogen
          - maim
          - gnome-keyring
          - dmenu
          - rofi
          - picom
          # - lightdm
          # - lightdm-gtk-greeter
          - sddm
          - network-manager-applet
      pacman:
        name: "{{xorg_packages}}"
        state: present
        update_cache: yes

    - name: Configure 
      become: true
      block:
        - name: Enable service
          service:
            name: sddm.service
            enabled: true

    - name: Install WM
      include_tasks: taskgroups/install_i3.yml
