- name: "Installing window manager"
  hosts: local
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Install X11
      become: true
      vars:
        xorg_packages:
          - xorg
          - xorg-xclock
          - xorg-xinit
          - xterm
          - xdg-utils
          - xclip
          - unclutter
          - nitrogen
          - maim
          - gnome-keyring
          - dmenu
          # - lightdm
          # - lightdm-gtk-greeter
          - sddm
          - network-manager-applet
      pacman:
        name: "{{xorg_packages}}"
        state: present
        update_cache: yes

    - name: Install aur packages for wm
      command:
        cmd: "paru -Syu --needed --noconfirm picom-simpleanims-git"

    # - name: Configure lightdm
      # become: true
      # block:
        # - name: "Configure lightdm"
          # lineinfile:
            # dest: /etc/lightdm/lightdm.conf
            # state: present
            # regexp: "^#greeter-session=.*$"
            # line: "greeter-session=lightdm-gtk-greeter"
        # - name: Enable service
          # service:
            # name: lightdm.service
            # enabled: true

    - name: Configure 
      become: true
      block:
        - name: Enable service
          service:
            name: sddm.service
            enable: true

    - name: Install WM
      include_tasks: taskgroups/install_i3.yml