- name: "Os setup"
  hosts: local
  vars_files:
    - "../vars.yml"
  vars_prompt:
    - name: root_passwd
      prompt: Root password
    - name: usr_passwd
      prompt: User password
  tasks:
    - name: "Installing packages from pacman"
      pacman:
        name: "{{pacman_packages | join(',')}}"
        state: present
        update_cache: yes

    - name: Setting up timezone
      command:
        cmd: "ln -sf /usr/share/zoneinfo/{{timezone}} /etc/localtime"

    - name: Adjusting time
      command:
        cmd: "hwclock --systohc"

    - name: Updating locales file
      loop: "{{locales}}"
      lineinfile:
        path: /etc/locale.gen
        regexp: "#({{item}}.*)$"
        line: '\1'
        backrefs: true

    - name: Generate locales
      command:
        cmd: locale-gen

    - name: "Create locale file"
      copy:
        dest: /etc/locale.conf
        content: |
          LANG={{locales[0]}}

    - name: Add hostname
      copy:
        dest: /etc/hostname
        content: |
          {{hostname}}

    - name: Update hosts
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost
          ::1         localhost

    - name: Create boot image
      command:
        cmd: mkinitcpio -P

    - name: Set root password
      user:
        name: "root"
        state: "present"
        password: "{{ root_passwd | password_hash('sha512') }}"

    - name: Create groups
      loop: "{{new_groups}}"
      group:
        name: "{{item}}"

    - name: Setup sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) ALL"
        validate: visudo -cf %s

    - name: Create user
      user:
        name: "{{username}}"
        create_home: true
        groups: "{{ new_groups | join(',') }},sudo"
        password: "{{ usr_passwd | password_hash('sha512') }}"
        shell: /bin/zsh

    - name: Install grub
      include_tasks: taskgroups/install_grub.yml

    - name: Install network manager
      pacman:
        name: networkmanager
        state: present
        update_cache: yes

    - name: Setting up NetworkManager service
      service:
        name: NetworkManager.service
        enabled: true
