- name: "Os setup"
  hosts: local
  vars_files:
    - "../vars.yml"
  tasks:
    - name: "Setting up time"
      command:
        cmd: "ln -sf /usr/share/zoneinfo/{{timezone}} /etc/localtime"
    - name: "Adjusting time"
      command:
        cmd: "hwclock --systohc"
    - name: "Updating locales file"
      loop: "{{locales}}"
      lineinfile:
        path: /etc/locale.gen
        regexp: "#({{item}}.*)"
        line: '\2'
        backrefs: true
    - name: "Generate locales"
      command:
        cmd: locale-gen
    - name: "Create locale file"
      copy:
        dest: /etc/locale.conf
        content: |
          LANG={{locales[0]}}
