- name: "Os setup"
  hosts: local
  vars_files:
    - "../vars.yml"
  tasks:
    - name: "Setting up time"
      ansible.builtin.command:
        cmd: "ln -sf /usr/share/zoneinfo/{{timezone}} /etc/localtime"
    - name: "Adjusting time"
      ansible.builtin.command:
        cmd: "hwclock --systohc"
    - name: "Updating locales file"
      loop: "{{locales}}"
      ansible.builtin.lineinfile:
        path: /etc/locale.gen
        regexp: "#({{item}} .*)"
        line: '\1'
        backrefs: true
