- name: "Installing dependencies"
  hosts: "local"
  vars_files:
    - "../vars.yml"
  tasks:

    - name: Setup Rust
      block:
        - name: Install rustup
          become: true
          pacman:
            name: rustup
            state: present
            update_cache: yes
        - name: Install stable toolchain
          command:
            cmd: rustup toolchain install stable
        - name: Setting default toolchain
          command:
            cmd: rustup default stable

    - name: Install AUR helper
      vars:
        item:
          git_url: https://aur.archlinux.org/paru.git
          build_command: yes | makepkg -fsri
      include_tasks: taskgroups/install_from_git.yml

    - name: "Install packages from AUR"
      command:
        cmd: "paru -Syu --needed --noconfirm {{aur_deps | join(' ')}}"

    - name: "Build packages from source"
      loop: "{{custom_packages}}"
      include_tasks: taskgroups/install_from_git.yml

    - name: "Copy dotfiles"
      loop: "{{dotenv_files}}"
      copy:
        src: "{{item['source']}}"
        dest: "{{item['dest']}}"